# Generated by Django 3.2.8 on 2021-10-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('goods_image', models.ImageField(default='img.png', upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'goods',
            },
        ),
    ]
