# Generated by Django 3.2.8 on 2021-10-15 00:46
import random

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='location',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.FloatField(default=random.randint(100, 200)),
            preserve_default=False,
        ),
    ]
